// search index for WYSIWYG Web Builder
var database_length = 0;

function SearchPage(url, title, keywords, description)
{
   this.url = url;
   this.title = title;
   this.keywords = keywords;
   this.description = description;
   return this;
}

function SearchDatabase()
{
   database_length = 0;
   this[database_length++] = new SearchPage("Home.html", "Melty Ice Cream Store", "Sweet perks for a sweet customer  SPLENDID  REWARDS  Get random rewards as you order frequently in our shop, get surprised as to what is inside on your next time ordering one of our delightful ice cream treats just for you!!  ICE CREAM CART   ", "");
   this[database_length++] = new SearchPage("Flavors-Page.html", "Melty Ice Cream Store (Flavors)", "ALL FLAVORS  Our order minimum is 5 pints But after that it's up to you Our boxes are designed to neatly hold up to 6, 9, or 18 pints  Guaranteed frozen delivery  Flat-rate shipping nationwide  Instagram worthy unboxing  A swirl of pink and white peppermint  with white chocolate freckles  Mouthwatering and rich, it’s like a  scoopable cherry cheesecake  A refreshing and subtly herbaceous cream  cheese ice cream with a crisp graham  cracker swirl  A swirl of white peppermint with white Fresh dairy sweetened with just enough cane sugar Minimal and beautiful — like frozen whipped cream   A far-out twist of blue brambleberry,  watermelon, and pink lemonade sorbets  Juicy orange ice cream with vanilla  custard and burnt orange caramel  Guaranteed frozen delivery Pints arrive in an insulated box with plenty of dry ice  Flat-rate shipping nationwide No matter how many pints you order  Instagram-worthy unboxing Pints are packaged with an artful attention to detail  Vanilla custard, raspberry jelly,  and a brown sugar   A refreshing and subtly herbaceous cream cheese ice cream with a crisp graham cracker swirl.Fluffy pancakes in salted butter and maple syrup creams  Real bananas, ultra-rich coconut cream,  and scratch-made vanilla wafers  Peanut butter, caramel, chocolate,  and pretzels in perfect harmony  ICE CREAM CART   ", "");
   this[database_length++] = new SearchPage("Most-Popular.html", "Melty Ice Cream Store (Most-Popular)", "MOST POPULAR  Treat yourself to the best! Our popular ice creams are made with the finest ingredients, bursting with flavor, and loved by everyone One scoop is never enough, indulge today and taste why they’re everyone’s favorite!  Guaranteed frozen delivery  Flat-rate shipping nationwide  Instagram worthy unboxing  Peppermint cream with crunchy,  bittersweet chocolate  Buttercream frosting, golden cake,  and a rainbow of sprinkles  Peanut butter, caramel, chocolate,  and pretzels in perfect harmony  Mouthwatering and rich, it’s like a  scoopable cherry cheesecake   Salted and roasted ground peanuts with grass-grazed milk and crunchy, dark chocolate flecks  Cream cheese ice cream layered with  crumbles of vanilla cake and a swirl of caramel-butterscotch sauce  Guaranteed frozen delivery Pints arrive in an insulated box with plenty of dry ice  Flat-rate shipping nationwide No matter how many pints you order  Instagram-worthy unboxing Pints are packaged with an artful attention to detail  Packed with Fair Trade cocoa  and not much else   Brown butter almond candy crushed into  buttercream ice cream  Scratch-made darkest chocolate cookies  with flecks of white chocolate in  vanilla-scented cream  Oven-toasted oat streusel and a sweet-tart brambleberry jam layered throughout  vanilla ice cream  ICE CREAM CART   ", "");
   this[database_length++] = new SearchPage("Dairy-Free.html", "Melty Ice Cream Store (Dairy-Free)", "DAIRY-FREE  Deliciously creamy, 100% dairy-free! Our dairy-free ice creams are made for everyone to enjoy rich in flavor, guilt-free, and perfect for a cool treat anytime Taste the difference today!  Guaranteed frozen delivery  Flat-rate shipping nationwide  Instagram worthy unboxing  Light and bright Slingshot Coffee cold  brew sorbet twisted with lush coconut cream  Punchy lemon curd, shortbread crust,  and rich coconut cream  Real bananas, ultra-rich coconut cream,  and scratch-made vanilla wafers  A far-out twist of blue brambleberry, watermelon,  and pink lemonade sorbets   Sangria-style frozen rosé with pear, strawberry,  and watermelon Refreshing and bright with a  tinge of tartness  Decadent chocolate cake crumbles,  bittersweet fudge, and palate-gripping cocoa  Guaranteed frozen delivery Pints arrive in an insulated box with plenty of dry ice  Flat-rate shipping nationwide No matter how many pints you order  Instagram-worthy unboxing Pints are packaged with an artful attention to detail  Complex and ethereal flavor from the best cocoa the world has to offer Finishes with an ultralight whiff of coconut cream   ICE CREAM CART   ", "");
   this[database_length++] = new SearchPage("Gluten-Free.html", "Melty Ice Cream Store (Gluten-Free)", "GLUTEN-FREE  Indulge without worry! Our gluten-free ice creams are packed with flavor, smooth, and safe for those avoiding gluten Treat yourself to a sweet, worry-free delight today!  Guaranteed frozen delivery  Flat-rate shipping nationwide  Instagram worthy unboxing  A far-out twist of blue brambleberry,  watermelon, and pink lemonade sorbets  Fresh dairy sweetened with just enough  cane sugar Minimal and beautiful — like frozen whipped cream  Mouthwatering and rich, it’s like a  scoopable cherry cheesecake  A swirl of pink and white peppermint  with white chocolate freckles   Juicy orange ice cream with vanilla  custard and burnt orange caramel  Real bananas, ultra-rich coconut cream,  and scratch-made vanilla wafers  Guaranteed frozen delivery Pints arrive in an insulated box with plenty of dry ice  Flat-rate shipping nationwide No matter how many pints you order  Instagram-worthy unboxing Pints are packaged with an artful attention to detail  Buttercream frosting, golden cake,  and a rainbow of sprinkles   Like an uber creamy, tart candied  watermelon  Tart and uber creamy lemon with  from-scratch blueberry jam in fresh cultured  buttermilk and cream  A buttery after dinner mint ice cream with white chocolate flecks  ICE CREAM CART   ", "");
   return this;
}
